import {Colors} from '@/src/constants/Colors';
import {moderateScale, verticalScale} from '@/src/util/responsiveDimension';
import fontFamily from '@/src/styles/fontFamily';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9F9F9',
  },
  backgroundGlowTop: {
    position: 'absolute',
    width: moderateScale(195),
    height: moderateScale(195),
    borderRadius: moderateScale(97.5),
    top: verticalScale(-90),
    left: moderateScale(-40),
    backgroundColor: 'rgba(170, 0, 29, 0.08)',
  },
  backgroundGlowBottom: {
    position: 'absolute',
    width: moderateScale(234),
    height: moderateScale(234),
    borderRadius: moderateScale(117),
    bottom: verticalScale(-110),
    right: moderateScale(-45),
    backgroundColor: 'rgba(215, 228, 239, 0.35)',
  },
  content: {
    flex: 1,
    paddingHorizontal: moderateScale(24),
    paddingTop: verticalScale(48),
    paddingBottom: verticalScale(28),
    justifyContent: 'center',
  },
  header: {
    alignItems: 'center',
    marginBottom: verticalScale(32),
  },
  title: {
    fontFamily: fontFamily.gaglin,
    fontSize: moderateScale(26),
    lineHeight: moderateScale(32),
    color: Colors.red,
    letterSpacing: moderateScale(2),
    textAlign: 'center',
    fontWeight: 'bold',
  },
  subtitle: {
    marginTop: verticalScale(8),
    fontFamily: fontFamily.regular,
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    color: '#546069',
    textAlign: 'center',
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: moderateScale(8),
    paddingHorizontal: moderateScale(24),
    paddingVertical: verticalScale(28),
    shadowColor: Colors.black,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.04,
    shadowRadius: 30,
    elevation: 3,
    gap: verticalScale(20),
  },
  fieldWrap: {
    gap: verticalScale(4),
  },
  fieldLabel: {
    fontFamily: fontFamily.medium,
    fontSize: moderateScale(12),
    lineHeight: moderateScale(16),
    color: '#546069',
    textAlign: 'left',
  },
  inputWrap: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(228, 189, 187, 0.5)',
    minHeight: verticalScale(40),
    justifyContent: 'center',
  },
  icon: {
    position: 'absolute',
    left: 0,
    bottom: verticalScale(12),
  },
  input: {
    fontFamily: fontFamily.regular,
    fontSize: moderateScale(14),
    color: Colors.black,
    textAlign: false ? 'right' : 'left',
    writingDirection: false ? 'rtl' : 'ltr',
    paddingVertical: 0,
    paddingHorizontal: moderateScale(2),
    paddingRight: false ? moderateScale(2) : moderateScale(28),
    paddingLeft: false ? moderateScale(28) : moderateScale(24),
  },
  passwordTopRow: {
    flexDirection: false ? 'row-reverse' : 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  forgotText: {
    fontFamily: fontFamily.regular,
    fontSize: moderateScale(14),
    lineHeight: moderateScale(15),
    color: Colors.red,
  },
  passwordIconButton: {
    position: 'absolute',
    right: 6,
    left: undefined,
    bottom: verticalScale(10),
    width: moderateScale(20),
    height: moderateScale(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  signInButton: {
    marginTop: verticalScale(10),
    borderRadius: moderateScale(6),
    overflow: 'hidden',
  },
  signInGradient: {
    minHeight: verticalScale(44),
    justifyContent: 'center',
    alignItems: 'center',
  },
  signInText: {
    fontFamily: fontFamily.medium,
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    color: Colors.white,
    textAlign: 'center',
  },
  footer: {
    marginTop: verticalScale(26),
    alignItems: 'center',
    gap: verticalScale(4),
  },
  footerNote: {
    fontFamily: fontFamily.regular,
    fontSize: moderateScale(12),
    lineHeight: moderateScale(16),
    color: '#546069',
    textAlign: 'center',
  },
  footerLink: {
    fontFamily: fontFamily.medium,
    fontSize: moderateScale(12),
    lineHeight: moderateScale(16),
    color: Colors.red,
    textAlign: 'center',
  },
});
