spring.application.name=tower
server.port=8080
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.formate-sql=true

secret.key=${SECRET_KEY}
file.upload-dir=src/main/java/com/towerManagementSystem/tower
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

#it will help starting app fast
spring.main.lazy-initialization=true
cloud.url=${CLOUD_URL}
