export const SCREEN_NAME={
    "USER_LOGIN":"USER_LOGIN",
    'USER_BOTTOM_TAB':'USER_BOTTOM_TAB',
    "LOGS":"LOGS",
    "RAISE_NEW_COMPLAINT":"RAISE_NEW_COMPLAINT",
    'TICKET_DETAILS':'TICKET_DETAILS',
    "ADD_POST":"ADD_POST",
    "NEW_TENANT":"NEW_TENANT",
    "TENANT_PROFILE":"TENANT_PROFILE",
    "POST_EDIT":"POSTEDIT",
    "TENANT_EDIT":"TENANT_EDIT",
    "TECHNICIAN_EDIT":"TECHNICIAN_EDIT",
    "NOTIFICATION":"NOTIFCATION",
    "NEW_TECHNICIAN":"NEW_TECHNICIAN",
    "TECHNICIANS_BOTTOM_TAB":"TECHNICIANS_BOTTOM_TAB",
   
}