import {Colors} from '@/src/constants/Colors';
import {
  horizontalScale,
  moderateScale,
  verticalScale,
} from '@/src/util/responsiveDimension';
import fontFamily from '@/src/styles/fontFamily';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  primary: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 16,
    paddingTop: verticalScale(10),
  },
  keyBoardAvoidingCont: {flex: 1, backgroundColor: '#F9F9F9', width: '100%'},
  btnContainer: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    backgroundColor: Colors.white,
    paddingHorizontal: horizontalScale(30),
    padding: horizontalScale(20),
    paddingBottom: verticalScale(40),
  },
  crossText: {
    fontSize: moderateScale(20),
    fontFamily: fontFamily.gaglin,
    fontWeight: 'bold',
    color: Colors.red,
  },
  imagePlaceHolder: {
    width: '100%',
    flexDirection: 'row',
    gap: 10,
  },
  secondary: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(16),
    paddingBottom: verticalScale(52),
    width: '100%',
  },
  updateImageBtn: {
    position: 'absolute',
    top: -10,
    right: -5,
    width: 30,
    height: 30,
    borderRadius: moderateScale(15),
    backgroundColor: Colors.darkGray,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryContainer: {
    height: '100%',
    borderTopLeftRadius: moderateScale(14),
    borderBottomLeftRadius: moderateScale(14),
    paddingLeft: horizontalScale(3),

    backgroundColor: Colors.red,
  },
  inputContainer: {
    padding: horizontalScale(10),
    width: '100%',
    backgroundColor: Colors.white,
    borderRadius: moderateScale(8),
  },
  section: {
    gap: verticalScale(16),
    backgroundColor: Colors.white,
  },
  sectionTitle: {
    fontFamily: fontFamily.bold,
    fontSize: moderateScale(18),
    lineHeight: moderateScale(28),
    color: '#1A1C1C',
    backgroundColor: Colors.white,
    textAlign: false ? 'right' : 'left',
  },
  descInput: {
    minHeight: verticalScale(120),
    paddingTop: verticalScale(12),
    paddingBottom: verticalScale(12),
  },
  titleInput: {
    minHeight: verticalScale(56),
  },
  inputBase: {
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(228, 189, 187, 0.2)',
    paddingHorizontal: moderateScale(16),
    justifyContent: 'center',
  },
  inputBackground: {
    backgroundColor: '#F3F3F3',
    borderRadius: moderateScale(6),
    padding: moderateScale(4),
  },
  inputText: {
    fontFamily: fontFamily.regular,
    fontSize: moderateScale(16),
    color: Colors.black,
    textAlign: false ? 'right' : 'left',
    writingDirection: false ? 'rtl' : 'ltr',
  },
  uploadBox: {
    borderRadius: moderateScale(6),
    borderWidth: 2,
    borderColor: 'rgba(228, 189, 187, 0.3)',
    borderStyle: 'dashed',
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: verticalScale(48),
    paddingHorizontal: moderateScale(20),
  },
  uploadIcon: {
    width: moderateScale(33),
    height: moderateScale(30),
    borderRadius: moderateScale(6),
    backgroundColor: '#AA001D',
    opacity: 0.2,
  },
  uploadTitle: {
    marginTop: verticalScale(12),
    fontFamily: fontFamily.medium,
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    color: '#546069',
    textAlign: 'center',
  },
  raiseButton: {
    borderRadius: moderateScale(6),
    minWidth: '30%',
    overflow: 'hidden',
    shadowColor: '#AA001D',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 3,
  },
  raiseButtonGradient: {
    minHeight: verticalScale(34),
    paddingHorizontal: moderateScale(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  raiseButtonText: {
    fontFamily: fontFamily.semiBold,
    fontSize: moderateScale(12),
    lineHeight: moderateScale(20),
    letterSpacing: moderateScale(0.35),
    color: Colors.white,
    fontWeight: 'bold',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: moderateScale(24),
  },
  modalCard: {
    width: '100%',
    borderRadius: moderateScale(12),
    backgroundColor: Colors.white,
    padding: moderateScale(16),
    gap: moderateScale(10),
  },
  modalTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: moderateScale(16),
    color: '#1A1C1C',
    textAlign: 'center',
    marginBottom: moderateScale(8),
  },
  modalActionButton: {
    minHeight: verticalScale(46),
    borderRadius: moderateScale(8),
    backgroundColor: '#F3F3F3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalActionText: {
    fontFamily: fontFamily.medium,
    fontSize: moderateScale(14),
    color: '#1A1C1C',
    textAlign: 'center',
  },
  modalCancelButton: {
    minHeight: verticalScale(42),
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancelText: {
    fontFamily: fontFamily.medium,
    fontSize: moderateScale(14),
    color: '#AA001D',
    textAlign: 'center',
  },
  photoList: {
    flexDirection: false ? 'row-reverse' : 'row',
    gap: moderateScale(8),
  },
  photoPreview: {
    width: moderateScale(72),
    height: moderateScale(72),
    borderRadius: moderateScale(8),
    backgroundColor: '#E5E7EB',
  },
  uploadSubtitle: {
    marginTop: verticalScale(4),
    fontFamily: fontFamily.regular,
    fontSize: moderateScale(12),
    lineHeight: moderateScale(16),
    color: '#BBC8D3',
    textAlign: 'center',
  },
});
