import {Colors} from '@/src/constants/Colors';
import {
  horizontalScale,
  moderateScale,
  verticalScale,
} from '@/src/util/responsiveDimension';
import fontFamily from '@/src/styles/fontFamily';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F9F9F9',
  },
  floatingBtn: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    height: 60,
    width: 60,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topBar: {
    height: verticalScale(92),
    paddingHorizontal: moderateScale(24),
    paddingTop: verticalScale(42),
    paddingBottom: verticalScale(14),
    backgroundColor: 'rgba(255,255,255,0.9)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(12),
  },
  avatar: {
    width: moderateScale(32),
    height: moderateScale(32),
    borderRadius: moderateScale(12),
    backgroundColor: '#D7E4EF',
  },
  brand: {
    fontFamily: fontFamily.bold,
    fontSize: moderateScale(18),
    lineHeight: moderateScale(28),
    color: Colors.bloodRed,
    letterSpacing: moderateScale(1.4),
  },

  content: {
    flex: 1,
    paddingHorizontal: moderateScale(24),
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  heading: {
    fontFamily: fontFamily.bold,
    fontSize: moderateScale(26),
    lineHeight: moderateScale(36),
    color: Colors.brownishBlack,
    textAlign: 'left',
  },
  subHeading: {
    marginTop: verticalScale(4),
    fontFamily: fontFamily.regular,
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    color: '#546069',
    textAlign: 'left',
  },
  raiseButton: {
    borderRadius: moderateScale(6),
    overflow: 'hidden',
    shadowColor: Colors.red,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 3,
  },
  raiseButtonGradient: {
    minHeight: verticalScale(34),
    paddingHorizontal: moderateScale(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  raiseButtonText: {
    fontFamily: fontFamily.semiBold,
    fontSize: moderateScale(12),
    lineHeight: moderateScale(20),
    letterSpacing: moderateScale(0.35),
    color:Colors.white,
  },
  list: {
    marginTop: verticalScale(24),
    paddingBottom: verticalScale(24),
    gap: verticalScale(16),
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: moderateScale(12),
    paddingHorizontal: horizontalScale(20),
    paddingVertical: verticalScale(20),
    shadowColor: '#1A1C1C',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.04,
    shadowRadius: 24,
    elevation: 2,
    borderLeftWidth: moderateScale(4),
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardTitleWrap: {
    flex: 1,
  },
  categoryPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#EEEEEE',
    borderRadius: moderateScale(2),
    paddingHorizontal: moderateScale(10),
    paddingVertical: verticalScale(4),
  },
  categoryText: {
    fontFamily: fontFamily.semiBold,
    fontSize: moderateScale(12),
    lineHeight: moderateScale(16),
    color: '#5B403E',
    letterSpacing: moderateScale(0.6),
  },
  cardTitle: {
    marginTop: verticalScale(8),
    fontFamily: fontFamily.bold,
    fontSize: moderateScale(18),
    lineHeight: moderateScale(28),
    color: Colors.brownishBlack,
    textAlign: 'left',
  },
  statusPill: {
    borderRadius: moderateScale(12),
    minWidth: moderateScale(78),
    paddingHorizontal: moderateScale(12),
    paddingVertical: verticalScale(4),
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(5),
    alignSelf: 'flex-start',
  },
  statusDot: {
    width: moderateScale(6),
    height: moderateScale(6),
    borderRadius: moderateScale(3),
  },
  statusText: {
    fontFamily: fontFamily.bold,
    fontSize: moderateScale(12),
    lineHeight: moderateScale(16),
    color: Colors.brownishBlack,
  },
  description: {
    marginTop: verticalScale(14),
    fontFamily: fontFamily.regular,
    fontSize: moderateScale(14),
    lineHeight: moderateScale(22),
    color: '#546069',
    textAlign: 'left',
  },
  cardFooter: {
    marginTop: verticalScale(14),
    borderTopWidth: 1,
    borderTopColor: 'rgba(232, 232, 232, 0.5)',
    paddingTop: verticalScale(12),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(4),
  },
  footerText: {
    fontFamily: fontFamily.regular,
    fontSize: moderateScale(12),
    lineHeight: moderateScale(16),
    color: '#49555A',
  },
  footerTxt: {
    fontFamily: fontFamily.regular,
    fontSize: moderateScale(12),
    lineHeight: moderateScale(16),
    color: Colors.black,
    textAlign: 'center',
  },
  tabButton: {
    width: '48%',
    paddingVertical: verticalScale(10),
    paddingHorizontal: horizontalScale(10),
    borderRadius: moderateScale(10),
  },
  tabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(10),
    flexWrap: 'wrap',
    gap: 8,
    rowGap: 10,
  },
  btnContentContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: horizontalScale(10),
  },
  textContent: {
    fontSize: moderateScale(14),
    fontFamily: fontFamily.medium,
    color: '#aaaaaa',
    fontWeight: 'bold',
  },
  textCnt: {
    fontSize: moderateScale(14),
    fontFamily: fontFamily.bold,
    fontWeight: 'bold',
    color: Colors.black,
  },
  footerTxtEnd: {
    color: Colors.gray,
    fontFamily: fontFamily.gaglin,
    textAlign: 'center',
    fontSize: moderateScale(16),
    paddingBottom: 10,
  },
  floatingBtnPrimary: {
    height: 60,
    width: 60,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
